import fs from "node:fs";
import { MemorySource } from "./src/byte-source.js";
import { IndexReader } from "./src/index-reader.js";
import { SearchSession } from "./src/search-session.js";
import { SessionContext } from "./src/session-context.js";
import { formatStats } from "./src/stats.js";
const reader = await IndexReader.open(new MemorySource(fs.readFileSync("web/public/demo.index")));
const s = new SearchSession(reader, "<aciimnrttu>", new SessionContext());
await s.run(300000, 50, () => {});
for (const line of formatStats(s.stats())) console.log("  " + line);
