// Regenerate the construct reference in the usage guide from the catalogue.
//
//   node scripts/build-docs.mjs          # rewrite web/public/usage.html
//   node scripts/build-docs.mjs --check  # fail if it is out of date
//
// The reference used to be written by hand next to the code that defines the
// constructs, which is a promise to keep two things in step forever. Now the
// catalogue carries each construct's summary and example, and this renders
// them; `--check` runs in CI, so adding a construct without documenting it
// fails the build rather than quietly shipping an incomplete guide.

import * as fs from "node:fs";

const FILE = "web/public/usage.html";
const START = "<!-- REFERENCE:START (generated by scripts/build-docs.mjs) -->";
const END = "<!-- REFERENCE:END -->";

const { CONSTRUCTS, GROUP_BLURB, qualifiedName } = await import(
  "../src/constructs.js"
);
const { listNames } = await import("../src/word-lists.js");

const ORDER = [
  "word",
  "count",
  "bag",
  "edit",
  "cipher",
  "spell",
  "shape",
  "match",
];

const esc = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const rows = [];
for (const group of ORDER) {
  const members = CONSTRUCTS.filter((c) => c.group === group);
  if (members.length === 0) continue;
  rows.push(
    `<h3 class="grp">${group}<span class="gb"> — ${esc(GROUP_BLURB[group])}</span></h3>`,
  );
  rows.push('<table class="ref">');
  for (const c of members) {
    // The example is a link, so every row in the reference is runnable.
    rows.push(
      `<tr><td><tt>${esc(qualifiedName(c))}</tt></td>` +
        `<td>${esc(c.summary)}</td>` +
        `<td><tt><a href="./?q=${encodeURIComponent(c.example)}">${esc(c.example)}</a></tt></td></tr>`,
    );
  }
  rows.push("</table>");
}

const generated = `${START}\n${rows.join("\n")}\n${END}`;

const html = fs.readFileSync(FILE, "utf8");
const from = html.indexOf(START);
const to = html.indexOf(END);
if (from === -1 || to === -1) {
  console.error(`${FILE}: missing ${START} / ${END} markers`);
  process.exit(2);
}
const updated = html.slice(0, from) + generated + html.slice(to + END.length);

/**
 * The README's feature table is written by hand — it describes features, not
 * constructs, so there is nothing to generate it from — and it drifts. It has
 * claimed that negation was "capped at 5000 states" after the cap was
 * removed, pointed at a "why?" button after the button was deleted, and
 * counted 26 built-in lists when there were 30.
 *
 * Prose cannot be checked. Two things in it can: every `{name:…}` it names
 * must be a construct that exists, and the count of built-in lists must be
 * the number there are. Both are exactly the claims that go stale silently,
 * because nothing breaks when they do.
 */
function checkReadme() {
  const readme = "README.md";
  if (!fs.existsSync(readme)) return [];
  const text = fs.readFileSync(readme, "utf8");
  const bad = [];

  const known = new Set(CONSTRUCTS.map((c) => c.name));
  // The README explains the language as well as listing it, so it writes
  // `{name:…}` and `{expr}` meaning "any of them". None of these is a
  // construct, and none may become one without this noticing.
  const PLACEHOLDERS = new Set(["name", "expr", "pattern"]);
  for (const p of PLACEHOLDERS) {
    if (known.has(p)) {
      bad.push(`"${p}" is now a construct and can no longer be a placeholder`);
    }
  }
  const seen = new Set();
  for (const m of text.matchAll(/`\{([a-z][a-z0-9.]*)\s*[:<>=+(]/gi)) {
    const raw = m[1].toLowerCase();
    const name = raw.slice(raw.lastIndexOf(".") + 1).replace(/\d+$/, "");
    if (seen.has(name) || PLACEHOLDERS.has(name)) continue;
    seen.add(name);
    if (!known.has(name) && !known.has(raw)) {
      bad.push(`README.md names {${raw}:…}, which is not a construct`);
    }
  }

  const claimed = /(\d+) shipped categories/.exec(text);
  if (claimed && Number(claimed[1]) !== listNames().length) {
    bad.push(
      `README.md says ${claimed[1]} shipped categories; there are ` +
        `${listNames().length}`,
    );
  }
  return bad;
}

if (process.argv.includes("--check")) {
  const readmeProblems = checkReadme();
  for (const p of readmeProblems) console.error(p);
  if (readmeProblems.length > 0) process.exit(1);
  if (updated !== html) {
    console.error(
      `${FILE} is out of date — run \`npm run build-docs\` and commit the result.`,
    );
    process.exit(1);
  }
  console.error(`${FILE}: reference is up to date (${CONSTRUCTS.length} constructs)`);
  process.exit(0);
}

fs.writeFileSync(FILE, updated);
console.error(`wrote ${CONSTRUCTS.length} constructs into ${FILE}`);
