// Regenerate the construct reference in the usage guide from the catalogue.
//
//   node scripts/build-docs.mjs          # rewrite web/public/usage.html
//   node scripts/build-docs.mjs --check  # fail if it is out of date
//
// The reference used to be written by hand next to the code that defines the
// constructs, which is a promise to keep two things in step forever. Now the
// catalogue carries each construct's summary and example, and this renders
// them; `--check` runs in CI, so adding a construct without documenting it
// fails the build rather than quietly shipping an incomplete guide.

import * as fs from "node:fs";

const FILE = "web/public/usage.html";
const START = "<!-- REFERENCE:START (generated by scripts/build-docs.mjs) -->";
const END = "<!-- REFERENCE:END -->";

const { CONSTRUCTS, GROUP_BLURB, qualifiedName } = await import(
  "../src/constructs.js"
);

const ORDER = [
  "word",
  "count",
  "bag",
  "edit",
  "cipher",
  "spell",
  "shape",
  "match",
  "out",
];

const esc = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const rows = [];
for (const group of ORDER) {
  const members = CONSTRUCTS.filter((c) => c.group === group);
  if (members.length === 0) continue;
  rows.push(
    `<h3 class="grp">${group}<span class="gb"> — ${esc(GROUP_BLURB[group])}</span></h3>`,
  );
  rows.push('<table class="ref">');
  for (const c of members) {
    // The example is a link, so every row in the reference is runnable.
    rows.push(
      `<tr><td><tt>${esc(qualifiedName(c))}</tt></td>` +
        `<td>${esc(c.summary)}</td>` +
        `<td><tt><a href="./?q=${encodeURIComponent(c.example)}">${esc(c.example)}</a></tt></td></tr>`,
    );
  }
  rows.push("</table>");
}

const generated = `${START}\n${rows.join("\n")}\n${END}`;

const html = fs.readFileSync(FILE, "utf8");
const from = html.indexOf(START);
const to = html.indexOf(END);
if (from === -1 || to === -1) {
  console.error(`${FILE}: missing ${START} / ${END} markers`);
  process.exit(2);
}
const updated = html.slice(0, from) + generated + html.slice(to + END.length);

if (process.argv.includes("--check")) {
  if (updated !== html) {
    console.error(
      `${FILE} is out of date — run \`npm run build-docs\` and commit the result.`,
    );
    process.exit(1);
  }
  console.error(`${FILE}: reference is up to date (${CONSTRUCTS.length} constructs)`);
  process.exit(0);
}

fs.writeFileSync(FILE, updated);
console.error(`wrote ${CONSTRUCTS.length} constructs into ${FILE}`);
