// GENERATED by scripts/build-lists.mjs — do not edit by hand.
//
// Large `{list:…}` categories sourced from Wikidata (CC0). Regenerate with
// `node scripts/build-lists.mjs`; the file is committed so clean clones and
// CI need no network. Small canonical sets are hand-written in word-lists.ts.
//
// Counts at generation time: countries 197, capitals 203, usstates 50, elements 175, constellations 90, greekgods 320, norsegods 70, dogbreeds 922, presidents 39.

export const GENERATED_LISTS: Record<string, string> = {
  countries:
    "afghanistan,albania,algeria,andorra,angola,antigua and barbuda," +
    "argentina,armenia,australia,austria,azerbaijan,bahrain,bangladesh," +
    "barbados,belarus,belgium,belize,benin,bhutan,bolivia," +
    "bosnia and herzegovina,botswana,brazil,brunei,bulgaria,burkina faso," +
    "burundi,cambodia,cameroon,canada,cape verde,central african republic," +
    "chad,chile,china,colombia,comoros,costa rica,croatia,cuba,cyprus," +
    "czech republic,democratic republic of the congo,denmark,djibouti," +
    "dominica,dominican republic,ecuador,egypt,el salvador," +
    "equatorial guinea,eritrea,estonia,eswatini,ethiopia," +
    "federated states of micronesia,fiji,finland,france,gabon,georgia," +
    "germany,ghana,greece,grenada,guatemala,guinea,guinea bissau,guyana," +
    "haiti,honduras,hungary,iceland,india,indonesia,iran,iraq,ireland," +
    "israel,italy,ivory coast,jamaica,japan,jordan,kazakhstan,kenya," +
    "kiribati,kosovo,kuwait,kyrgyzstan,laos,latvia,lebanon,lesotho,liberia," +
    "libya,liechtenstein,lithuania,luxembourg,madagascar,malawi,malaysia," +
    "maldives,mali,malta,marshall islands,mauritania,mauritius,mexico," +
    "moldova,monaco,mongolia,montenegro,morocco,mozambique,myanmar,namibia," +
    "nauru,nepal,new zealand,nicaragua,niger,nigeria,north korea," +
    "north macedonia,norway,oman,pakistan,palau,palestine,panama," +
    "papua new guinea,paraguay,peru,philippines,poland,portugal,qatar," +
    "romania,russia,rwanda,saint kitts and nevis,saint lucia," +
    "saint vincent and the grenadines,samoa,san marino," +
    "sao tome and principe,saudi arabia,senegal,serbia,seychelles," +
    "sierra leone,singapore,slovakia,slovenia,solomon islands,somalia," +
    "south africa,south korea,south sudan,spain,sri lanka,sudan,suriname," +
    "sweden,switzerland,syria,taiwan,tajikistan,tanzania,thailand," +
    "the bahamas,the congo,the gambia,the netherlands,timor leste,togo," +
    "tonga,trinidad and tobago,tunisia,turkey,turkmenistan,tuvalu,uganda," +
    "ukraine,united arab emirates,united kingdom,united states,uruguay," +
    "uzbekistan,vanuatu,vatican city,venezuela,vietnam,yemen,zambia," +
    "zimbabwe",
  capitals:
    "abu dhabi,abuja,accra,addis ababa,aden,algiers,amman,amsterdam," +
    "andorra la vella,ankara,antananarivo,apia,ashgabat,asmara,astana," +
    "asuncion,athens,baghdad,baku,bamako,bandar seri begawan,bangkok," +
    "bangui,banjul,basseterre,beijing,beirut,belgrade,belmopan,berlin,bern," +
    "bishkek,bissau,bloemfontein,bogota,brasilia,bratislava,brazzaville," +
    "bridgetown,brussels,bucharest,budapest,buenos aires,cairo,canberra," +
    "cape town,caracas,castries,chisinau,ciudad de la paz,colombo,conakry," +
    "copenhagen,dakar,damascus,dhaka,dili,djibouti,dodoma,doha,dublin," +
    "dushanbe,east jerusalem,freetown,funafuti,gaborone,georgetown,gitega," +
    "guatemala city,hanoi,harare,havana,helsinki,honiara,islamabad,jakarta," +
    "jerusalem,juba,kabul,kampala,kathmandu,khartoum,kigali,kingston," +
    "kingstown,kinshasa,kuala lumpur,kuwait city,kyiv,la paz,libreville," +
    "lilongwe,lima,lisbon,ljubljana,lobamba,lome,london,luanda,lusaka," +
    "luxembourg,madrid,majuro,male,managua,manama,manila,maputo,maseru," +
    "mbabane,mexico city,minsk,mogadishu,monaco,monrovia,montevideo,moroni," +
    "moscow,muscat,nairobi,nassau,naypyidaw,ndjamena,new delhi,ngerulmud," +
    "niamey,nicosia,nouakchott,nuku alofa,oslo,ottawa,ouagadougou,palikir," +
    "panama city,paramaribo,paris,phnom penh,podgorica,port au prince," +
    "port louis,port moresby,port of spain,port vila,porto novo,prague," +
    "praia,pretoria,pristina,pyongyang,quito,rabat,ramallah,reykjavik,riga," +
    "riyadh,rome,roseau,san jose,san marino,san salvador,sanaa,santiago," +
    "santo domingo,sao tome,sarajevo,seoul,singapore,skopje,sofia," +
    "south tarawa,sri jayawardenepura kotte,st georges,stockholm,sucre," +
    "suva,taipei,tallinn,tashkent,tbilisi,tegucigalpa,tehran,thimphu," +
    "tirana,tokyo,tripoli,tunis,ulaanbaatar,vaduz,valletta,vatican city," +
    "victoria,vienna,vientiane,vilnius,warsaw,washington d c,wellington," +
    "windhoek,yamoussoukro,yaounde,yaren district,yerevan,zagreb",
  usstates:
    "alabama,alaska,arizona,arkansas,california,colorado,connecticut," +
    "delaware,florida,georgia,hawaii,idaho,illinois,indiana,iowa,kansas," +
    "kentucky,louisiana,maine,maryland,massachusetts,michigan,minnesota," +
    "mississippi,missouri,montana,nebraska,nevada,new hampshire,new jersey," +
    "new mexico,new york,north carolina,north dakota,ohio,oklahoma,oregon," +
    "pennsylvania,rhode island,south carolina,south dakota,tennessee,texas," +
    "utah,vermont,virginia,washington,west virginia,wisconsin,wyoming",
  elements:
    "actinium,aluminium,americium,antimony,argon,arsenic,astatine,barium," +
    "berkelium,beryllium,bismuth,bohrium,boron,bromine,cadmium,caesium," +
    "calcium,californium,carbon,cerium,chlorine,chromium,cobalt," +
    "copernicium,copper,curium,darmstadtium,distributed feedback laser," +
    "dubnium,dysprosium,einsteinium,erbium,europium,fermium,flerovium," +
    "fluorine,francium,gadolinium,gallium,germanium,gold,hafnium,hassium," +
    "helium,holmium,hydrogen,indium,iodine,iridium,iron,krypton,lanthanum," +
    "lawrencium,lead,lithium,livermorium,lutetium,magnesium,manganese," +
    "meitnerium,mendelevium,mercury,molybdenum,moscovium,neodymium,neon," +
    "neptunium,nickel,nihonium,niobium,nitrogen,nobelium,oganesson,osmium," +
    "oxygen,palladium,phosphorus,platinum,plutonium,polonium,potassium," +
    "praseodymium,promethium,protactinium,radium,radon,rhenium,rhodium," +
    "roentgenium,rubidium,ruthenium,rutherfordium,samarium,scandium," +
    "seaborgium,selenium,silicon,silver,sodium,strontium,sulfur,tantalum," +
    "technetium,tellurium,tennessine,terbium,thallium,thorium,thulium,tin," +
    "titanium,tungsten,unbibium,unbiennium,unbihexium,unbinilium," +
    "unbioctium,unbipentium,unbiquadium,unbiseptium,unbitrium,unbiunium," +
    "unhexbium,unhexennium,unhexhexium,unhexnilium,unhexoctium," +
    "unhexpentium,unhexquadium,unhexseptium,unhextrium,unhexunium," +
    "unoctquadium,unpentbium,unpentennium,unpenthexium,unpentnilium," +
    "unpentoctium,unpentpentium,unpentquadium,unpentseptium,unpenttrium," +
    "unpentunium,unquadbium,unquadennium,unquadhexium,unquadnilium," +
    "unquadoctium,unquadpentium,unquadquadium,unquadseptium,unquadtrium," +
    "unquadunium,unseptbium,unseptnilium,unsepttrium,unseptunium,untribium," +
    "untriennium,untrihexium,untrinilium,untrioctium,untripentium," +
    "untriquadium,untriseptium,untritrium,untriunium,ununennium,uranium," +
    "vanadium,xenon,ytterbium,yttrium,zinc,zirconium",
  constellations:
    "andromeda,antlia,apus,aquarius,aquila,ara,auriga,bootes,caelum," +
    "camelopardalis,canes venatici,canis major,canis minor,capricornus," +
    "carina,cassiopeia,centaurus,cepheus,cetus,chamaeleon,circinus,columba," +
    "coma berenices,corona australis,corona borealis,corvus,crater,crux," +
    "cygnus,delphinus,dorado,draco,equuleus,eridanus,fornax,gemini," +
    "gladii electorales saxonici,grus,hercules,horologium,hydra,hydrus," +
    "indus,lacerta,leo,leo minor,lepus,libra,lupus,lynx,lyra," +
    "marmor sculptile,mensa,microscopium,monoceros,musca,norma,octans," +
    "ophiuchus,orion,pavo,pegasus,perseus,phoenix,pictor,pisces," +
    "piscis austrinus,puppis,pyxis,reticulum,sagitta,sagittarius,sah," +
    "sciurus volans,scorpius,sculptor,scutum,serpens,sextans,taurus," +
    "telescopium,triangulum,triangulum australe,tucana,ursa major," +
    "ursa minor,vela,virgo,volans,vulpecula",
  greekgods:
    "acesis,aceso,acmon,acratus,adephagia,adikia,adonis,adranus,adrasteia," +
    "adrestia,aegle,aeolus,aergia,aesa,aescolanus,agathe tyche," +
    "agathodaemon,agdistis,aglaea,aidos,aion,alcidemos,alea,algos," +
    "amalcides,amechania,amicitia,amphictyonis,amphiona,amphitrite,angelia," +
    "angelos,anius,anteros,antheia,aphaea,apheleia,aphrodite," +
    "aphrodite akraia,aphrodite of the gardens,aphroditus,apollo," +
    "apollo maleatas,apotropaei,ares,arete,aristaeus,arke,artemis," +
    "artemis of ephesus,artemis persica,artemis tauropolos,ascanius," +
    "asclepius,aspis,astarte,astraea,astrape,atabyrius,athena,athena areia," +
    "athena chalcioecus,athena polias,athena promachos,atropos,auxesia," +
    "auxo,basile,basileia,bendis,benthesikyme,bia,biris,bonus deus," +
    "borysthenis,britomartis,brizo,byne,cadmilus,caerus,caligine," +
    "calligeneia,calumny,carpo,caryatis,caystrus,chaldean hekate,charon," +
    "cheimon,chthon,circe,cithaeron,cleta,clotho,clymenus,comus,conisalus," +
    "corymbus,cotys,crotus,ctesius,cybele,daemogorgon,damia,deima,deimos," +
    "demeter,demeter eleusinia,demokratia,demos,despoina,dicaeosyne,dike," +
    "dionysus,dodonian zeus,dolor,dolos,dyssebeia,echidna,eiar,eileithyia," +
    "eirene,ekecheiria,elais,eleos,eleutheria,eleutherus,elpis,enipeus," +
    "enodia,enyalius,enyo,eos,epiales,epidotai,epikrateia,epiphron,eris," +
    "eros,euamerion,eucleia,eudaemonia,eulabeia,eunomia,eunostus," +
    "euphrosyne,euposia,eupraxia,eurynome,euthymia,evonyme,fysei,galene," +
    "gelos,genetyllides,glycon,gymnastike,gynaikeia,hades,harmonia," +
    "harpocrates,hebe,hecate,hecate epipyrgidia,hedylogos,heimarmene," +
    "helicon,helios,hemera,hepat,hephaestus,hera,hera alexandros," +
    "hermaphroditus,hesperus,hestia,himeros,homados,homonoia,horme,hygieia," +
    "hylates,hymen,hypate,hypnos,iacchus,icelus,ichnaea,imbrasus,ioke,iris," +
    "itonia,kakia,kallone,karneios,keltos,keuthonymos,koalemos," +
    "kourotrophos,kratos,lachesis,limos,lype,lyssa,meilichius,melinoe," +
    "menae,mese,messembria,mise,molis,momus,moros,morpheus,myiodes,neaera," +
    "neikea,nemesis,nestis,nete,nike,nomos,oberon,oeno,onga,opora,oreius," +
    "orion,orthanes,osiris dionysus,ossa,paean,palaemon,palaistra,palioxis," +
    "pallas,pamisus,pan,pan sybarios,panacea,pandemos,pandia,pandora," +
    "paralia,paregoros,pasikrata,pasithea,peitharchia,penia,penthus," +
    "pepromene,persephone,phaenna,phantasos,phaunos,pheme,pherousa," +
    "philomelus,philophrosyne,phobetor,phobos,phobos and deimos,phoebus," +
    "phosphorus,phrike,phthonus,physis,plane,plutus,poena,poene,poseidon," +
    "pothos,praxidice,prodomeis,proioxis,promylaia,prophasis,pseudea," +
    "psyche,pthinoporon,ptocheia,pyrrhichos,sabazius,sardus,scelmis,selene," +
    "serapis,socus,sophrosyne,sosipolis,soter,spermo,spudaion,staphylus," +
    "stratius,tekmor,telesphorus,temenius,thalia,thallo,thanatos," +
    "theandrios,theros,thesmophoros,thrasos,thyia,thyone,titaea,triclaria," +
    "tychon,unknown gods,venus anadyomene,zagreus,zelus,zeus,zeus ammon," +
    "zeus cassius,zeus georgos,zeus soter",
  norsegods:
    "alako,alfadur,annar,baldur,bragi,dellingr,eir,fjorgyn,fjorgynn," +
    "forseti,freyja,freyr,frigg,friggs mother,fulla,gaut,gefjon,ger r,gir," +
    "glenr,gna,h nir,heimdall,hel,hermod,hlin,ho r,i unn,ilmr," +
    "ingunar freyr,irpa,jor,kari,kvasir,lo urr,lofn,loki,magni,meili,mimir," +
    "mo i,nanna,nepr,njord,njorun,o r,odin,oku thor,orger r holgabru r,ran," +
    "rig,saga,sigyn,sister wife of njor r,sjofn,ska i,snotra,sol," +
    "sons of odin,syn,thor,tyr,ull,vali,var,ve,veraldur,vi arr,vili,vor",
  dogbreeds:
    "abruzzo maremma sheepdog,abyssinian sand terrier," +
    "adirondack pointing dog,affenpinscher,afghan hound,afghan mastiff," +
    "afghan spaniel,african village dog,africanis,agassaei,agassin,aidi," +
    "airedale terrier,akbash,akita,aksaray malaklisi dog,alano," +
    "alano espanol,alapaha blue blood bulldog,alaskan klee kai," +
    "alaskan malamute,albanian mountain dog,albanian wolfdog,alicant dog," +
    "alopekis,alpine dachsbracke,ameri indian alaskan husky,american akita," +
    "american alsatian,american blue gascon hound,american bulldog," +
    "american bully,american cocker spaniel,american english coonhound," +
    "american eskimo dog,american foxhound,american hairless terrier," +
    "american leopard hound,american mastiff,american pit bull terrier," +
    "american squirrel dog,american staffordshire terrier," +
    "american staghound,american water spaniel,american wolfdog," +
    "american working red,anatolian greyhound,anatolian shepherd," +
    "andalusian hound,anglo russian hound,anglo spanish greyhound," +
    "antebellum bulldog,appalachian sighthound,appenzeller sennenhund," +
    "aquarius,argentine pila dog,argentine polar dog,ariege pointer," +
    "ariegeois,armant dog,armenian gampr dog,artesien normand,artois hound," +
    "assyrian mastiff,aurora husky,aussiedoodle,australasian bosdog," +
    "australian barb,australian cattle dog,australian cobberdog," +
    "australian kelpie,australian shepherd,australian silky terrier," +
    "australian staghound,australian stock dog," +
    "australian stumpy tail cattle dog,australian terrier," +
    "austrian black and tan hound,austrian pinscher,auvergne shepherd," +
    "awa ken,azawakh,azores cattle dog,bac ha dog,badger dog,baganda dog," +
    "bajan toy terrier,bakharwal dog,bakhmull,balla terrier," +
    "bangara mastiff,barak hound,barbado da terceira,barbet," +
    "barrocal algarvio,basati alaunt,basenji,basque shepherd dog,basset," +
    "basset artesien normand,basset bleu de gascogne,basset dartois," +
    "basset hound,batak dog,bavarian mountain hound,beagle,beagle harrier," +
    "beaglier,bearded collie,beauceron,bedlington terrier,belgian griffons," +
    "belgian malinois,belgian mastiff,belgian pointer,belgian shepherd," +
    "bergamasco shepherd,berger de crau,berner laufhund,bernese hound," +
    "bernese mountain dog,beskydsky bundas,bichon frise,bichon yorkie," +
    "biewer terrier,billy,bisben,bisharin greyhound," +
    "black and tan coonhound,black and tan terrier," +
    "black and tan virginia foxhound,black mouth cur,black norrlandshund," +
    "black norwegian elkhound,black pointer,black russian terrier," +
    "black slovakian shepherd,black spitz,bloodhound,blue gascony griffon," +
    "blue lacy,blue picardy spaniel,bluetick coonhound,boerboel," +
    "boerenfox terrier,bohemian shepherd,bohemian spotted dog,bolognese," +
    "bolonka franzuska,bone mouth,borador,border collie,border terrier," +
    "borneo dog,borzoi,boston terrier,bouvier des ardennes," +
    "bouvier des flandres,boxador,boxer,boykin spaniel,bracco italiano," +
    "branchiero siciliano,braque charles x,braque dauvergne," +
    "braque du bourbonnais,braque du puy,braque francais," +
    "braque saint germain,brazilian bull mastiff,brazilian terrier,briard," +
    "briquet de provence,briquet griffon vendeen,brittany,brittany spaniel," +
    "broholmer,bruno jura hound,buckhound,bucovina shepherd dog,bulgae," +
    "bulgarian hound,bulgarian scenthound,bulgarian shepherd dog," +
    "bull and terrier,bull arab,bull boxer,bull terrier,bullbras,bulldog," +
    "bullmastiff,bullnese,bully kutta,burgos retriever,burmese spitz dog," +
    "buryat mongolian wolfhound,ca de conills,ca me mallorqui," +
    "cairn terrier,calupoh,camas cur,campeiro bulldog,camus cur," +
    "can de chira,can de palleiro,canaan dog,canadian cur," +
    "canadian eskimo dog,cane corso,cane pecoraio varbutu,cane toccatore," +
    "canis panther,cantabrian water dog,cao de gado transmontano," +
    "capheaton terrier,cardigan welsh corgi,carea castellano manchego," +
    "carolina cur,carolina dog,carpathian shepherd dog," +
    "catahoula leopard dog,catalan sheepdog,caucasian shepherd dog," +
    "cavalier king charles spaniel,celtic hounds," +
    "central asian shepherd dog,cesky fousek,cesky horsky pes," +
    "cesky terrier,cesky wire haired pointing griffon,chamuco," +
    "chesapeake bay retriever,chien blanc du roi," +
    "chien francais blanc et noir,chihuahua,chilean dogo," +
    "chilean fox terrier,chinese chongqing dog,chinese crested dog," +
    "chinese happa dog,chinese hound,chinese imperial dog,chinook," +
    "chippiparai,chorkie,chortai,chow chow,chuandong hound," +
    "chukotka sled dog,cimarron uruguayo,circassian orloff wolfhound," +
    "cirneco delletna,clallam indian dog,clumber spaniel,cocker spaniel," +
    "cojack,colima dog,collie,combai,comforter,common indian dog," +
    "continental bulldog,continental toy spaniel,coonhound," +
    "cordoba fighting dog,coton de tulear,creeper terrier,cretan hound," +
    "croatian sheepdog,cur dog,curly coated retriever,cursinu," +
    "cyprus poodle,czechoslovakian wolfdog,dachshund,daito inu,dalmatian," +
    "damchi,dandie dinmont terrier,danish spitz,danish swedish farmdog," +
    "decker terrier,deltari ilir,denmark feist,deutsche bracke,dingo," +
    "dinka greyhound,dobermann,dogo argentino,dogo espanol,dogo sardesco," +
    "dogue brasileiro,dogue de bordeaux,dong gyeong," +
    "double nosed andean tiger hound,drentse patrijshond,drever,dropper," +
    "dumfriesshire hound,dunker,dutch shepherd,dutch smoushond," +
    "dutch tulip dog,east european shepherd,east siberian laika," +
    "ecuadorian hairless dog,egyptian hairless dog,english bull terrier," +
    "english cocker spaniel,english foxhound,english mastiff," +
    "english pointer,english setter,english shepherd," +
    "english springer spaniel,english toy terrier,english water spaniel," +
    "entlebucher mountain dog,erbi txakur,estonian hound," +
    "estrela mountain dog,eurasier,farm collie,faroese sheepdog," +
    "fawn brittany basset,fawn brittany griffon,fell hound,field labrador," +
    "field spaniel,fila brasileiro,finnish hound,finnish lapphund," +
    "finnish spitz,flat coated retriever,formosan mountain dog,fox terrier," +
    "francais blanc et orange,french bulldog,french charnaigre dog," +
    "french hound,french pointing dog gascogne type," +
    "french pointing dog pyrenean type,french spaniel," +
    "french tricolour hound,frenchton,friesian windhund,fu quan," +
    "fuegian dog,galgo china,gascon saintongeois,gaucho sheepdog,gegar," +
    "georgian shepherd,gerberian shepsky,german longhaired pointer," +
    "german pinscher,german shepherd,german shorthaired pointer," +
    "german silky pinscher,german spaniel,german spitz,german spitz mittel," +
    "german wirehaired pointer,giant schnauzer,glen of imaal terrier," +
    "glenwherry collie,golden retriever,gollie,gordon setter,gorskaja," +
    "gos datura aranes,gos rater valencia,gotland hound,grahund," +
    "gran mastin de borinquen,grand fauve de bretagne," +
    "grand gascon saintongeois,grand griffon vendeen," +
    "great anglo french tricolour hound," +
    "great anglo french white and black hound,great dane," +
    "great gascony blue,greater swiss mountain dog,grecian greyhound," +
    "gredin spaniel,greek harehound,greek shepherd,greenland dog,greyhound," +
    "greyster,griffon,griffon a poil laineux,griffon belge," +
    "griffon bruxellois,griffon nivernais,gro spitz,groenendael," +
    "guatemalan dogo,guicho,gull dong,gull terr,hairless dog," +
    "hairless khala,halden hound,halleforshund,hamiltonstovare,han dog," +
    "hanover hound,harlequin pinscher,harrier,havanese,hedehund," +
    "hertha pointer,himalayan sheepdog,hmong bobtail dog,hokkaido inu," +
    "hovawart,hungarian sheepdog,huntaway,huslia husky,hygen hound," +
    "ibizan hound,icelandic sheepdog,illyrian shepherd,inca dog," +
    "indian husky,indian spitz,indian tailles dog,inn kwe," +
    "irish red and white setter,irish setter," +
    "irish staffordshire bull terrier,irish terrier,irish water spaniel," +
    "irish wolfhound,istrian coarse haired hound,istrian shorthaired hound," +
    "italian greyhound,italian rough haired segugio,iwate inu," +
    "izcuintli itzcuintli,jack russell terrier,jagdterrier,jamthund," +
    "japanese chin,japanese spitz,japanese terrier,jeju dog,jomon dog," +
    "jonangi,juan fernandez sheepdog,kai ken,kanawar dog," +
    "kangal shepherd dog,kanni,karakachan dog,karelian bear dog," +
    "karelo finnish laika,kars dog,karst shepherd,kattai dog,kawakami ken," +
    "kazakh tazy,keeshond,kemmer stock cur,kentucky shell heap dog," +
    "kerry beagle,kerry blue terrier,king charles spaniel,king shepherd," +
    "kintamani,kishu,kitler,klamath indian dog,kleinspitz,kokoni,komondor," +
    "konigsberger paukenhund,kooikerhondje,koolie,korean jindo dog," +
    "korean mastiff,koshi,koshikiyama inu,koyun dog,kromfohrlander,kumis," +
    "kunma dog,kunming wolfdog,kurdish mastiff,kurdistan greyhound,kuvasz," +
    "labrador retriever,labrit,laconian,laconian hound,laekenois," +
    "lagotto romagnolo,lai dog,laizhou red dog,lakeland foxhound," +
    "lakeland terrier,lancashire heeler,landseer,laobe,lapponian herder," +
    "lapponian shepherd,large munsterlander,large vendeen griffon basset," +
    "latvian hound,leavitt bulldog,leonberger,leopard tree dog," +
    "lessinia and lagorai shepherd,levesque,levriero meridionale," +
    "lhasa apso,liangshan dog,limer,lithuanian hound,llewellin setter," +
    "lobito herreno,long haired dachshund,long haired inca dog," +
    "longhaired whippet,lottatore brindisino,lowchen,lucas terrier," +
    "lucernese hound,lupo italiano,lyme mastiff,macedonian karaman," +
    "magyar agar,majestic tree hound,majorca shepherd dog,mallorcan ratter," +
    "maltese,maltese fox terrier,maltese little lion dog," +
    "maltese pocket dog,manchester terrier,maneto,mantiqueira shepherd," +
    "marxdorfer wolfshund,matin,medelyan,medium sized anglo french hound," +
    "meitei hui,mexican lapdog,mi ki,miniature american shepherd," +
    "miniature australian shepherd,miniature bull terrier," +
    "miniature dachshund,miniature fox terrier,miniature pinscher," +
    "miniature schnauzer,miniature shar pei,miniature siberian husky," +
    "mioritic,mojee,molossian,molossian hound,molossus of epirus,mongrel," +
    "montenegrin mountain hound,morkie,moscow watchdog,moscow water dog," +
    "mountain cur,mountain feist,mountain view cur,mucuchies,mudhol hound," +
    "mudi,mullins feist,multi colored poodle,murcian ratter," +
    "murray river curly coated retriever,naga dog,national deerhound," +
    "native irish pedigree dog breeds,neapolitan mastiff," +
    "nenets herding laika,new guinea singing dog,new zealand heading dog," +
    "newfoundland dog,nootka dog,norfolk terrier,norman hound," +
    "normand poitevin,norrbottenspets,north easthrly haaling laika," +
    "northern inuit dog,northern terrier,northwest farm terrier," +
    "norwegian buhund,norwegian elkhound,norwegian lundehund," +
    "norwich terrier,nova scotia duck tolling retriever,nureongi,odis," +
    "old croatian sighthound,old danish pointer,old english sheepdog," +
    "old time farm shepherd,old welsh grey sheepdog,olde english bulldogge," +
    "oriental shar pei,original cajun squirrel dog," +
    "original fila brasileiro,otterhound,pachon navarro,paisley terrier," +
    "pampas deerhound,pandikona,papillon,pardog,pariah dog," +
    "parson russell terrier,pashmi hound,pastor americano,pastore fonnese," +
    "patagonian bearded greyhound,patagonian sheepdog,patterdale terrier," +
    "patti,pekingese,pembroke welsh corgi,perdigueiro galego," +
    "perro de pastor garafiano,perro de presa mallorquin," +
    "perro fino colombiano,perro majorero,perro pampa argentino," +
    "peruvian hairless dog,peruvian inca orchid," +
    "petit basset griffon vendeen,petit bleu de gascogne,petit brabancon," +
    "petit gascon saintongeois,phalene,pharaoh hound," +
    "philippines islands dog,phu quoc ridgeback dog,picardy shepherd," +
    "picardy spaniel,piccolo segugio dellappennino,pit bullmastiff," +
    "pit monster,plains indian dog,plott hound,pocket beagle," +
    "podenco canario,podenco palmero,podengo galego,poitevin hound," +
    "poligar hound,polish greyhound,polish hound,polish hunting dog," +
    "polish hunting spaniel,polish lowland sheepdog,poltalloch terrier," +
    "polynesian dog,pomeranian wolf dog,pomsky,pont audemer spaniel," +
    "poochon,poodle,porcelaine,portuguese cattle dog,portuguese podengo," +
    "portuguese pointer,portuguese sheepdog,portuguese water dog," +
    "posavac hound,powinder dog,prapsos,prazsky krysarik,presa canario," +
    "pudelpointer,pueblo dog,pug,puli,pulin,pumi,pungsan,pyrenean mastiff," +
    "pyrenean mountain dog,pyrenean sheepdog long haired," +
    "pyrenean sheepdog smooth faced,pyrenean shepherd,rafeiro do alentejo," +
    "rajapalayam,ramanadhapuram mandai,ramanathapuram mandai dog," +
    "rampur greyhound,rare breed,rastreador brasileiro,rat terrier," +
    "ratonero basco,ratonero bodeguero andaluz cooper,ratonero palmero," +
    "red decoy dog,redbone coonhound,renascence bulldogge," +
    "rhodesian ridgeback,romanian raven shepherd dog,rothbury terrier," +
    "rottweiler,rough collie,ruby spaniel,running walker coonhound," +
    "russian hound,russian setter,russian spaniel," +
    "russkaya tsvetnaya bolonka,russkiy toy,russo european laika," +
    "ryukyu inu,saarloos wolfdog,sabueso espanol,saint usuge spaniel," +
    "saluki,samoyed,sanin shiba inu,sanshu,sapsali,sarabi mastiff," +
    "sarail hound,satsuma dog,savoy sheepdog,schafpudel,schapendoes," +
    "schillerstovare,schipperke,schwarzer,schweizer laufhund," +
    "schweizerischer niederlaufhund,schwyz hound,scotch collie," +
    "scottish deerhound,scottish terrier,sealyham terrier,segugio cravin," +
    "segugio dellappennino,segugio italiano,segugio italiano a pelo raso," +
    "segugio maremmano,seppala siberian sleddog,serbian hound," +
    "serbian sheep dog,serbian tricolour hound,serbian yellow hound," +
    "serrano bulldog,sertanejo dog,seskar seal dog,shakhi,shar pei," +
    "shelburne terrier,shepweiler,shetland sheepdog,shiba inu,shih tzu," +
    "shikoku ken,shilluk greyhound,shiloh shepherd,shorty bull," +
    "shropshre terrier,siberian husky,siberian sheepdog,sicilian sheepdog," +
    "sila shepherd,silken windhound,silken windsprite,silky spitz," +
    "sioux dog,skye terrier,sloughi,slovak cuvac," +
    "slovakian rough haired pointer,slovensky kopov,smaland hound," +
    "small me imurje dog,small munsterlander,smithfield,smooth collie," +
    "smooth fox terrier,soft coated wheaten terrier,south african mastiff," +
    "spanish mastiff,spanish water dog,sparta sheepdog,spino siciliano," +
    "spinone italiano,sporting lucas terrier,st bernard,st domingo dog," +
    "st hubert,st hubert jura hound,stabijhoun,staffordshire bull terrier," +
    "staghound,standard schnauzer,steinbracke,stephens cur,stichelhaar," +
    "strathdoon dingo killer,strobel,styrian coarse haired hound," +
    "sulimov dog,sussex spaniel,svensk vit alghund,swedish lapphund," +
    "swedish vallhund,tahitian dog,taigan,taimyr,takayasu inu,talbot," +
    "targhee hound,tarsus catalburuns,tatra shepherd dog,tatransky duric," +
    "techichi,teddy roosevelt terrier,telomian,tenterfield terrier," +
    "terceira mastiff,terry,tervuren,thai bangkaew dog,thai ridgeback," +
    "tibetan hound,tibetan kyi apso,tibetan mastiff,tibetan spaniel," +
    "tibetan terrier,timber wolf dog,timons biter,tong gau,tonya finosu," +
    "tornjak,tosa,toy bull terrier,toy fox terrier,toy manchester terrier," +
    "toy mi ki,toy munchkin,toy poodle,trailhound," +
    "transcaucasian mountain dog,transylvanian hound,treeing cur," +
    "treeing feist,treeing tennessee brindle,treeing walker coonhound," +
    "tripuri dog,tumbler,turkish greyhound,turkmen alabai," +
    "tuvinskaya ovcharka,tyrolean hound,u s state dogs,ukrainian sheepdog," +
    "ukrainian vivcharka,vaghari dog,valdueza,valley bulldog," +
    "victorian bulldog,villano de las encartaciones,vizsla," +
    "volpino italiano,waeller,walker foxhound,water drawer,weimaraner," +
    "welsh black and tan sheepdog,welsh blue grey,welsh corgi," +
    "welsh harrier,welsh hillman,welsh hound,welsh sheepdog," +
    "welsh springer spaniel,welsh terrier,west country harrier," +
    "west greenland dog,west highland white terrier,west siberian laika," +
    "westfal terrier,westiepoo,westphalian dachsbracke,wetterhoun,whippet," +
    "white english bulldog,white greek sheepdog,white shepherd dog," +
    "white swiss shepherd,wire fox terrier,wire haired beagle," +
    "wire haired dachshund,wirehaired pointing griffon,wirehaired vizsla," +
    "working pit bulldog,wurttemberg pointer,xarnego valenciano,xiasi dog," +
    "xigou,xoloitzcuintle,yakki dog,yakushima inu,yakutian laika," +
    "yorkshire terrier,yugoslavian shepherd dog,zande dog," +
    "zanzibar greyhound,zerdava,zlatiborski ovcar,zuchon",
  presidents:
    "adams,biden,buchanan,bush,carter,cleveland,clinton,coolidge," +
    "eisenhower,fillmore,ford,garfield,grant,harding,harrison,hayes,hoover," +
    "jackson,jefferson,johnson,kennedy,lincoln,madison,mckinley,monroe," +
    "nixon,obama,pierce,polk,reagan,roosevelt,taft,taylor,truman,trump," +
    "tyler,van buren,washington,wilson",
};
